apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcalc-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcalc-api
  template:
    metadata:
      labels:
        app: devcalc-api
    spec:
      containers:
        - name: devcalc-api
          image: devcalc-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080